services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-exapp
    ports:
      - "8086:8000"
    env_file: .env
    environment:
      MONGO_DETAILS: mongodb://mongo:27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-exapp
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    env_file: .env

volumes:
  mongo_data:
